### ISSUE TITLE
导入DNS设置后报错

### ISSUE THREAD

**Issue by Alcatraz1337** [chenxv399/v2ray-rules-dat#1]
您好，按照Readme中的操作 更新V2rayN之后（版本：V5.9），更换了提供的Geoip.dat和Geosite.dat，在更新DNS设置后，控制台报出以下错误，请指点哪里操作错误了吗？万分感谢！
`[Info] main/json: Reading config: D:\Application\v2rayN\config.json
Failed to start: main: failed to load config files: [D:\Application\v2rayN\config.json] > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid IP rule: [geoip:!cn] > infra/conf: failed to load GeoIP: !cn > infra/conf: code not found in geoip.dat: !CN
2022/04/04 01:23:09 Using default config:  D:\Application\v2rayN\config.json
`

**Comment by chenxv399** [comment]
首先很感谢您对项目提出的问题。但很抱歉，由于我并不是本项目的专业开发者，以下解决方案仅我个人意见，如果未能够解决您的问题，您可以访问Readme中提到的原项目的issues提交问题。错误代码中报错```config.json```文件无法读取，无法读取的具体原因为DNS设置错误和在```geoip.dat```文件中找不到geoip:!cn的规则。针对前一个错误，由于我并不知道您的设置过程是怎样的，我的建议是您在```设置```-```参数设置```-```Core:DNS设置```中，重新粘贴如下代码，粘贴时请保持英文输入环境。
```
{
  "hosts": {
    "dns.google": "8.8.8.8",
    "dns.pub": "119.29.29.29",
    "dns.alidns.com": "223.5.5.5",
    "geosite:category-ads-all": "127.0.0.1",
    "dns.cloudflare.com": "1.1.1.1",
    "aws.amazon.com":"169.254.169.253"
  },
  "servers": [
    {
      "address": "https://1.1.1.1/dns-query",
      "domains": ["geosite:geolocation-!cn"],
      "expectIPs": ["geoip:!cn"]
    },
    "8.8.8.8",
    {
      "address": "114.114.114.114",
      "port": 53,
      "domains": ["geosite:cn", "geosite:category-games@cn"],
      "expectIPs": ["geoip:cn"],
      "skipFallback": true
    },
    {
      "address": "localhost",
      "skipFallback": true
    }
  ]
}
```

**Comment by chenxv399** [comment]
而针对后一个错误，有多种可能性。
1、首先请尝试重新下载```geoip```和```geosite```文件，并确保您已正确替换原来的这两个文件而不是共存。您的错误似乎告诉我geoip文件是错误的，由于路由rules和DNS设置中的规则都指向此文件，所以请先确保这两个文件是替换后的文件。这里需要注意一下，v2rayn的geo文件可能会自动更新为官方的最新文件，请在替换后关闭自动更新geo文件，在```v2rayn设置```里勾选更新Core时忽略GEO文件。
2、请检查您的DNS规则设置是否正确。错误报告中提到geoip:!cn这条规则无法在geoip文件中找到，请确保您的规则输入时均使用英文字符输入，尤其是```!```和```:```。如果您完全是将我的规则粘贴到v2rayn中，在部分计算机由于github字体原因可能会出现错误的字符，建议您先将代码粘贴至记事本，检查是否有错误的字符或者中文化的字符。
3、可能是原项目中的geoip文件发生了改动。出现这种情况我也无能为力，您只能访问原项目联系原作者，毕竟我并非该项目的原始开发人员。

**Comment by chenxv399** [comment]
如果所有的解决方案都没法解决您的问题，终极的解决方案是您可以把我已经设置好的v2rayn直接下载到您的电脑上使用。由于v2rayn项目已经更新到5.11版本了，也不排除新版本的规则设置发生了更改的情况。我会把我的整个v2rayn 4.36版本上传到releases供大家下载。4.36版本并没有缺少必要的连接性功能，但可能缺少最新的一些新功能，在此请求谅解。

**Comment by reinkin** [comment]
我也碰到同样的问题，geoip.dat也在
墙内：https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
墙外：https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat 
包括Loyalsoldier提供的地址里下载过好几个版本
估计是5.9的新规则造成的问题？如果想针对性的修改有什么好的建议吗？

多谢啦！

**Comment by chenxv399** [comment]
@reinkin 我目前的解决办法是先在老版本，比方说4.xx版本的v2rayn里把规则先导入进去，然后只更新v2rayn客户端（注意一定不要更新geoip和geosite，v2fly或x-tls核心可以看情况更新），这样旧版本的规则就可以随着版本更新自动整理到新版本里面去。
初步判断引起这一问题的原因可能有两个：一是5.xx版本相比于老版本在功能上做出了过大的更新和改动，路由规则的编写格式发生了改变，导致新版本的v2rayn无法识别我写教程时候的老版本的json文件；另一个原因也可能是原作者的geoip和geosite的格式在更新后发生了改变，使得路由规则的格式同样需要修改。
由于最近比较忙，可能过一阵子我会针对新版本重写路由规则，到时候这个问题可能会有所改善。

**Comment by chenxv399** [comment]
@reinkin 我刚刚已经在多个系统上对V2rayN v5.9进行了测试，包括Windows 11, Windows 10和Windows 7，但很遗憾，在这三个系统版本上都没有出现您所提到的问题。同时我还对v5.16 beta版本和v4.36老版本进行了测试，也没有出现类似的问题。这说明规则文件不管是在最新的V2rayN上，还是最新的Geoip和Geosite环境下都可以正常使用。所以很抱歉，这一错误似乎仅出现于个别用户身上，这可能是由于您电脑的运行环境或者其他未知原因而导致的未知错误。不过您不用担心，配置好的V2rayN v5.9最新版本已经上传至releases，您可以访问本项目的releases下载后添加服务器直接使用，无需您手动配置。

**Comment by reinkin** [comment]
@chenxv399 虽然不知道是什么问题，不过下载了最新的release就可以了。多谢啦！
