### ISSUE TITLE
能写一个GFWlist的新版规则吗？我觉的这个很好用

### ISSUE THREAD

**Issue by Fengikjing** [chenxv399/v2ray-rules-dat#3]
https://github.com/gfwlist/gfwlist这个是GFWlist项目，新版的我不知道咋弄

**Comment by chenxv399** [comment]
很抱歉由于前段时间实在太忙了，我没能及时更新这个项目。可能过一阵子我会更新这个项目，加入新的规则，更新GEO文件。到时候新版的GFWlist可能会被加入其中。

**Comment by chenxv399** [comment]
版本更新已完成，规则文件已更新。请下载最新版本使用。
