### ISSUE TITLE
可不可能可以加一个适配~ 自动走最快的节点

### ISSUE THREAD

**Issue by ColinYYCC** [chenxv399/v2ray-rules-dat#4]
如題

**Comment by chenxv399** [comment]
很抱歉，本项目只负责编写和配置v2rayN的规则，让其变得更加好用。您提出的issue无法在规则层面修改，建议您前往v2rayN官方项目下提出issue[2dust/v2rayN](https://github.com/2dust/v2rayN)。
事实上，目前的v2rayN还没有这个自动选择最快节点的功能，您可以手动测速并选择节点，或者通过修改各个服务器的配置文件实现负载均衡（不建议小白这么干）。当然，如果您实在迫切需要这个功能，我推荐您使用[Clash](https://github.com/Dreamacro/clash)，这个软件相比于v2rayN似乎更加符合您的需要。
